apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviestreaming-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movie-dev
  template:
    metadata:
      labels:
        app: movie-dev
    spec:
      containers:
      - name: frontend-moviestreaming
        image: persevcareers/custom-images:netflix-v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-creds
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: LoadBalancer
  selector:
    app: movie-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
